name: Feature
description: Add a new feature
title: "[FEATURE]: As a ____, I want to ____, so I can ____."
labels: ["feature"]

body:
  - type: textarea
    attributes:
      label: Acceptance Criteria
      value: "
      - [ ] ...\n
      - [ ] ...\n
      - [ ] ...\n
      "

