name: 👷 Job Story
description: Propose a new feature or improvement in the form of a Job Story
title: '👷 [Summary]'
labels: ["feature", "job story"]

body:
  - type: markdown
    attributes:
      value: |
        # Submit a Job Story
        Job Stories help us focus on the tasks users are trying to accomplish. Please frame the feature from the perspective of the user's job. Your Job Story should not be tied to a specific solution, but rather to the user's context, motivation, and desired outcome.

  - type: dropdown
    attributes:
      label: User Type
      description: Who is the user in the job story?
      options:
        - Alumni
        - Case Worker
        - Coach
        - Employer
        - Potential Student
        - Recruiter
        - Student
      multiple: true
    validations:
      required: true

  - type: textarea
    attributes:
      label: Situation
      description: What situation triggers the user's need to perform the job? (When ____)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Motivation
      description: What is the user trying to achieve? (They want to ____)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Outcome
      description: What outcome does the user expect by performing the job? (So they can ____)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Metrics
      description: How will we measure if the proposed solution helps the user achieve the desired outcome?
    validations:
      required: true
