name: Feature
description: Add a new feature
title: "[FEATURE]:"
labels: ["enhancement"]

body:
  - type: textarea
    attributes:
      label: Title
      value: As a ____, I want to, ____ , so that ____
    validations:
      required: true
  - type: textarea
    attributes:
      label: Acceptance Criteria
      value: "
      - [ ] ...
      - [ ] ...
      - [ ] ...
      "

