name: Feature
description: Add a new feature
title: "[FEATURE]:"
labels: ["enhancement"]

body:
  - type: textarea
    attributes:
      label: Title
      value: As a ____, I want to, ____ , so that ____
    validations:
      required: true

  - type: markdown
    attributes:
      value: "
      - [ ] Acceptance Criteria 1
      - [ ] Acceptance Criteria 2
      - [ ] Acceptance Criteria 3
      "

    validations:
      required: true