// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */

import { initFormatters } from "./formatters";
import type { Locales, Translations } from "./i18n-types";
import { loadedFormatters, loadedLocales, locales } from "./i18n-util";

import de from "./de";
import en from "./en";

import de_apply from "./de/apply";
import de_signup from "./de/signup";
import en_apply from "./en/apply";
import en_signup from "./en/signup";

const localeTranslations = {
  de: {
    ...de,
    apply: de_apply,
    signup: de_signup,
  },
  en: {
    ...en,
    apply: en_apply,
    signup: en_signup,
  },
};

export const loadLocale = (locale: Locales): void => {
  if (loadedLocales[locale]) return;

  loadedLocales[locale] = localeTranslations[locale] as unknown as Translations;
  loadFormatters(locale);
};

export const loadAllLocales = (): void => locales.forEach(loadLocale);

export const loadFormatters = (locale: Locales): void =>
  void (loadedFormatters[locale] = initFormatters(locale));
