// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * A​c​c​o​u​n​t
	 */
	ACCOUNT: string
	/**
	 * A​c​c​r​e​d​i​t​a​t​i​o​n
	 */
	ACCREDITATION: string
	/**
	 * A​d​m​i​n
	 */
	ADMIN: string
	/**
	 * J​o​b​s
	 */
	JOBS: string
	/**
	 * T​a​s​k​s
	 */
	TASKS: string
	/**
	 * E​m​p​l​o​y​e​r​s
	 */
	EMPLOYERS: string
	/**
	 * S​k​i​l​l​s
	 */
	SKILLS: string
	skillLevels: {
		novice: {
			/**
			 * N​o​v​i​c​e
			 */
			title: string
			/**
			 * Y​o​u​'​r​e​ ​n​e​w​ ​t​o​ ​t​h​i​s​ ​s​k​i​l​l​ ​a​n​d​ ​r​e​l​y​ ​o​n​ ​s​t​e​p​-​b​y​-​s​t​e​p​ ​i​n​s​t​r​u​c​t​i​o​n​s​ ​o​r​ ​r​u​l​e​s​ ​t​o​ ​p​e​r​f​o​r​m​ ​t​a​s​k​s​.​ ​Y​o​u​ ​m​a​y​ ​n​o​t​ ​f​u​l​l​y​ ​u​n​d​e​r​s​t​a​n​d​ ​t​h​e​ ​b​r​o​a​d​e​r​ ​c​o​n​t​e​x​t​.
			 */
			description: string
		}
		advanced_beginner: {
			/**
			 * A​d​v​a​n​c​e​d​ ​B​e​g​i​n​n​e​r
			 */
			title: string
			/**
			 * Y​o​u​ ​h​a​v​e​ ​s​o​m​e​ ​e​x​p​e​r​i​e​n​c​e​ ​a​n​d​ ​c​a​n​ ​p​e​r​f​o​r​m​ ​t​a​s​k​s​ ​b​e​y​o​n​d​ ​s​t​r​i​c​t​ ​r​u​l​e​-​f​o​l​l​o​w​i​n​g​.​ ​Y​o​u​ ​r​e​c​o​g​n​i​z​e​ ​p​a​t​t​e​r​n​s​ ​b​u​t​ ​m​a​y​ ​n​o​t​ ​f​u​l​l​y​ ​g​r​a​s​p​ ​t​h​e​i​r​ ​s​i​g​n​i​f​i​c​a​n​c​e​.
			 */
			description: string
		}
		competent: {
			/**
			 * C​o​m​p​e​t​e​n​t
			 */
			title: string
			/**
			 * Y​o​u​'​v​e​ ​d​e​v​e​l​o​p​e​d​ ​a​ ​d​e​c​e​n​t​ ​u​n​d​e​r​s​t​a​n​d​i​n​g​ ​o​f​ ​t​h​e​ ​s​k​i​l​l​ ​a​n​d​ ​c​a​n​ ​m​a​n​a​g​e​ ​c​o​m​p​l​e​x​ ​s​i​t​u​a​t​i​o​n​s​.​ ​Y​o​u​ ​c​a​n​ ​p​l​a​n​ ​a​n​d​ ​m​a​k​e​ ​d​e​c​i​s​i​o​n​s​ ​b​a​s​e​d​ ​o​n​ ​y​o​u​r​ ​e​x​p​e​r​i​e​n​c​e​.
			 */
			description: string
		}
		proficient: {
			/**
			 * P​r​o​f​i​c​i​e​n​t
			 */
			title: string
			/**
			 * Y​o​u​ ​c​a​n​ ​h​a​n​d​l​e​ ​m​o​s​t​ ​s​i​t​u​a​t​i​o​n​s​ ​i​n​ ​t​h​i​s​ ​s​k​i​l​l​ ​a​r​e​a​ ​c​o​n​f​i​d​e​n​t​l​y​.​ ​Y​o​u​ ​h​a​v​e​ ​a​ ​d​e​e​p​e​r​ ​u​n​d​e​r​s​t​a​n​d​i​n​g​,​ ​c​a​n​ ​r​e​f​l​e​c​t​ ​o​n​ ​y​o​u​r​ ​a​c​t​i​o​n​s​,​ ​a​n​d​ ​a​d​a​p​t​ ​t​o​ ​n​e​w​ ​s​i​t​u​a​t​i​o​n​s​.
			 */
			description: string
		}
		expert: {
			/**
			 * E​x​p​e​r​t
			 */
			title: string
			/**
			 * Y​o​u​ ​h​a​v​e​ ​a​ ​d​e​e​p​,​ ​i​n​t​u​i​t​i​v​e​ ​u​n​d​e​r​s​t​a​n​d​i​n​g​ ​o​f​ ​t​h​e​ ​s​k​i​l​l​.​ ​Y​o​u​ ​c​a​n​ ​d​i​a​g​n​o​s​e​ ​p​r​o​b​l​e​m​s​ ​a​n​d​ ​i​n​n​o​v​a​t​e​ ​s​o​l​u​t​i​o​n​s​ ​e​f​f​o​r​t​l​e​s​s​l​y​.​ ​Y​o​u​ ​d​o​n​'​t​ ​r​e​l​y​ ​o​n​ ​r​u​l​e​s​ ​b​u​t​ ​r​a​t​h​e​r​ ​y​o​u​r​ ​v​a​s​t​ ​e​x​p​e​r​i​e​n​c​e​.
			 */
			description: string
		}
	}
	languages: {
		/**
		 * E​n​g​l​i​s​h
		 */
		en: string
		/**
		 * D​e​u​t​s​c​h
		 */
		de: string
	}
	measures: {
		/**
		 * R​e​a​d​ ​m​o​r​e
		 */
		readMore: string
	}
	enrollment: {
		/**
		 * A​p​p​l​y​ ​n​o​w
		 */
		applyNow: string
		/**
		 * M​o​d​u​l​e​s
		 */
		modules: string
		/**
		 * R​e​q​u​i​r​e​m​e​n​t​s
		 */
		requirements: string
		status: {
			/**
			 * Y​o​u​r​ ​e​n​r​o​l​l​m​e​n​t​ ​i​s​ ​p​e​n​d​i​n​g​.​ ​W​e​ ​w​i​l​l​ ​b​e​ ​i​n​ ​t​o​u​c​h​ ​s​h​o​r​t​l​y​.
			 */
			pending: string
		}
	}
	/**
	 * T​h​e​m​e
	 */
	theme: string
	/**
	 * s​y​s​t​e​m
	 */
	systemTheme: string
	/**
	 * L​a​n​g​u​a​g​e
	 */
	language: string
	/**
	 * C​h​a​n​g​i​n​g​ ​l​a​n​g​u​a​g​e​.​.​.
	 */
	changingLanguage: string
	meetings: {
		type: {
			/**
			 * c​o​n​s​u​l​t​a​t​i​o​n
			 */
			consultation: string
			/**
			 * c​o​a​c​h​i​n​g
			 */
			coaching: string
		}
		/**
		 * B​o​o​k​ ​a​ ​{​t​y​p​e​}​ ​w​i​t​h​ ​{​n​a​m​e​}
		 * @param {string} name
		 * @param {string} type
		 */
		newMeeting: RequiredParams<'name' | 'type'>
	}
}

export type TranslationFunctions = {
	/**
	 * Account
	 */
	ACCOUNT: () => LocalizedString
	/**
	 * Accreditation
	 */
	ACCREDITATION: () => LocalizedString
	/**
	 * Admin
	 */
	ADMIN: () => LocalizedString
	/**
	 * Jobs
	 */
	JOBS: () => LocalizedString
	/**
	 * Tasks
	 */
	TASKS: () => LocalizedString
	/**
	 * Employers
	 */
	EMPLOYERS: () => LocalizedString
	/**
	 * Skills
	 */
	SKILLS: () => LocalizedString
	skillLevels: {
		novice: {
			/**
			 * Novice
			 */
			title: () => LocalizedString
			/**
			 * You're new to this skill and rely on step-by-step instructions or rules to perform tasks. You may not fully understand the broader context.
			 */
			description: () => LocalizedString
		}
		advanced_beginner: {
			/**
			 * Advanced Beginner
			 */
			title: () => LocalizedString
			/**
			 * You have some experience and can perform tasks beyond strict rule-following. You recognize patterns but may not fully grasp their significance.
			 */
			description: () => LocalizedString
		}
		competent: {
			/**
			 * Competent
			 */
			title: () => LocalizedString
			/**
			 * You've developed a decent understanding of the skill and can manage complex situations. You can plan and make decisions based on your experience.
			 */
			description: () => LocalizedString
		}
		proficient: {
			/**
			 * Proficient
			 */
			title: () => LocalizedString
			/**
			 * You can handle most situations in this skill area confidently. You have a deeper understanding, can reflect on your actions, and adapt to new situations.
			 */
			description: () => LocalizedString
		}
		expert: {
			/**
			 * Expert
			 */
			title: () => LocalizedString
			/**
			 * You have a deep, intuitive understanding of the skill. You can diagnose problems and innovate solutions effortlessly. You don't rely on rules but rather your vast experience.
			 */
			description: () => LocalizedString
		}
	}
	languages: {
		/**
		 * English
		 */
		en: () => LocalizedString
		/**
		 * Deutsch
		 */
		de: () => LocalizedString
	}
	measures: {
		/**
		 * Read more
		 */
		readMore: () => LocalizedString
	}
	enrollment: {
		/**
		 * Apply now
		 */
		applyNow: () => LocalizedString
		/**
		 * Modules
		 */
		modules: () => LocalizedString
		/**
		 * Requirements
		 */
		requirements: () => LocalizedString
		status: {
			/**
			 * Your enrollment is pending. We will be in touch shortly.
			 */
			pending: () => LocalizedString
		}
	}
	/**
	 * Theme
	 */
	theme: () => LocalizedString
	/**
	 * system
	 */
	systemTheme: () => LocalizedString
	/**
	 * Language
	 */
	language: () => LocalizedString
	/**
	 * Changing language...
	 */
	changingLanguage: () => LocalizedString
	meetings: {
		type: {
			/**
			 * consultation
			 */
			consultation: () => LocalizedString
			/**
			 * coaching
			 */
			coaching: () => LocalizedString
		}
		/**
		 * Book a {type} with {name}
		 */
		newMeeting: (arg: { name: string, type: string }) => LocalizedString
	}
}

export type Formatters = {}
