// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type {
  BaseTranslation as BaseTranslationType,
  LocalizedString,
  RequiredParams,
} from "typesafe-i18n";

export type BaseTranslation = BaseTranslationType & DisallowNamespaces;
export type BaseLocale = "en";

export type Locales = "de" | "en";

export type Translation = RootTranslation & DisallowNamespaces;

export type Translations = RootTranslation & {
  apply: NamespaceApplyTranslation;
  signup: NamespaceSignupTranslation;
};

type RootTranslation = {
  /**
   * A​c​c​o​u​n​t
   */
  ACCOUNT: string;
  /**
   * A​c​c​r​e​d​i​t​a​t​i​o​n
   */
  ACCREDITATION: string;
  /**
   * A​d​m​i​n
   */
  ADMIN: string;
  /**
   * J​o​b​s
   */
  JOBS: string;
  /**
   * T​a​s​k​s
   */
  TASKS: string;
  /**
   * E​m​p​l​o​y​e​r​s
   */
  EMPLOYERS: string;
  /**
   * S​k​i​l​l​s
   */
  SKILLS: string;
  skillLevels: {
    novice: {
      /**
       * N​o​v​i​c​e
       */
      title: string;
      /**
       * Y​o​u​'​r​e​ ​n​e​w​ ​t​o​ ​t​h​i​s​ ​s​k​i​l​l​ ​a​n​d​ ​r​e​l​y​ ​o​n​ ​s​t​e​p​-​b​y​-​s​t​e​p​ ​i​n​s​t​r​u​c​t​i​o​n​s​ ​o​r​ ​r​u​l​e​s​ ​t​o​ ​p​e​r​f​o​r​m​ ​t​a​s​k​s​.​ ​Y​o​u​ ​m​a​y​ ​n​o​t​ ​f​u​l​l​y​ ​u​n​d​e​r​s​t​a​n​d​ ​t​h​e​ ​b​r​o​a​d​e​r​ ​c​o​n​t​e​x​t​.
       */
      description: string;
    };
    advanced_beginner: {
      /**
       * A​d​v​a​n​c​e​d​ ​B​e​g​i​n​n​e​r
       */
      title: string;
      /**
       * Y​o​u​ ​h​a​v​e​ ​s​o​m​e​ ​e​x​p​e​r​i​e​n​c​e​ ​a​n​d​ ​c​a​n​ ​p​e​r​f​o​r​m​ ​t​a​s​k​s​ ​b​e​y​o​n​d​ ​s​t​r​i​c​t​ ​r​u​l​e​-​f​o​l​l​o​w​i​n​g​.​ ​Y​o​u​ ​r​e​c​o​g​n​i​z​e​ ​p​a​t​t​e​r​n​s​ ​b​u​t​ ​m​a​y​ ​n​o​t​ ​f​u​l​l​y​ ​g​r​a​s​p​ ​t​h​e​i​r​ ​s​i​g​n​i​f​i​c​a​n​c​e​.
       */
      description: string;
    };
    competent: {
      /**
       * C​o​m​p​e​t​e​n​t
       */
      title: string;
      /**
       * Y​o​u​'​v​e​ ​d​e​v​e​l​o​p​e​d​ ​a​ ​d​e​c​e​n​t​ ​u​n​d​e​r​s​t​a​n​d​i​n​g​ ​o​f​ ​t​h​e​ ​s​k​i​l​l​ ​a​n​d​ ​c​a​n​ ​m​a​n​a​g​e​ ​c​o​m​p​l​e​x​ ​s​i​t​u​a​t​i​o​n​s​.​ ​Y​o​u​ ​c​a​n​ ​p​l​a​n​ ​a​n​d​ ​m​a​k​e​ ​d​e​c​i​s​i​o​n​s​ ​b​a​s​e​d​ ​o​n​ ​y​o​u​r​ ​e​x​p​e​r​i​e​n​c​e​.
       */
      description: string;
    };
    proficient: {
      /**
       * P​r​o​f​i​c​i​e​n​t
       */
      title: string;
      /**
       * Y​o​u​ ​c​a​n​ ​h​a​n​d​l​e​ ​m​o​s​t​ ​s​i​t​u​a​t​i​o​n​s​ ​i​n​ ​t​h​i​s​ ​s​k​i​l​l​ ​a​r​e​a​ ​c​o​n​f​i​d​e​n​t​l​y​.​ ​Y​o​u​ ​h​a​v​e​ ​a​ ​d​e​e​p​e​r​ ​u​n​d​e​r​s​t​a​n​d​i​n​g​,​ ​c​a​n​ ​r​e​f​l​e​c​t​ ​o​n​ ​y​o​u​r​ ​a​c​t​i​o​n​s​,​ ​a​n​d​ ​a​d​a​p​t​ ​t​o​ ​n​e​w​ ​s​i​t​u​a​t​i​o​n​s​.
       */
      description: string;
    };
    expert: {
      /**
       * E​x​p​e​r​t
       */
      title: string;
      /**
       * Y​o​u​ ​h​a​v​e​ ​a​ ​d​e​e​p​,​ ​i​n​t​u​i​t​i​v​e​ ​u​n​d​e​r​s​t​a​n​d​i​n​g​ ​o​f​ ​t​h​e​ ​s​k​i​l​l​.​ ​Y​o​u​ ​c​a​n​ ​d​i​a​g​n​o​s​e​ ​p​r​o​b​l​e​m​s​ ​a​n​d​ ​i​n​n​o​v​a​t​e​ ​s​o​l​u​t​i​o​n​s​ ​e​f​f​o​r​t​l​e​s​s​l​y​.​ ​Y​o​u​ ​d​o​n​'​t​ ​r​e​l​y​ ​o​n​ ​r​u​l​e​s​ ​b​u​t​ ​r​a​t​h​e​r​ ​y​o​u​r​ ​v​a​s​t​ ​e​x​p​e​r​i​e​n​c​e​.
       */
      description: string;
    };
  };
  languages: {
    /**
     * E​n​g​l​i​s​h
     */
    en: string;
    /**
     * D​e​u​t​s​c​h
     */
    de: string;
  };
  measures: {
    /**
     * O​u​r​ ​c​o​u​r​s​e​s
     */
    heading: string;
    /**
     * L​e​a​r​n​ ​m​o​r​e
     */
    readMore: string;
    /**
     * A​s​ ​a​n​ ​A​Z​A​V​ ​c​e​r​t​i​f​i​e​d​ ​e​d​u​c​a​t​i​o​n​a​l​ ​i​n​s​t​i​t​u​t​i​o​n​,​ ​w​e​ ​o​f​f​e​r​ ​f​u​l​l​y​ ​a​c​c​r​e​d​i​t​e​d​ ​c​o​u​r​s​e​s​ ​d​e​s​i​g​n​e​d​ ​t​o​ ​m​e​e​t​ ​t​h​e​ ​h​i​g​h​e​s​t​ ​s​t​a​n​d​a​r​d​s​ ​o​f​ ​q​u​a​l​i​t​y​ ​a​n​d​ ​e​f​f​e​c​t​i​v​e​n​e​s​s​.
     */
    intro: string;
  };
  enrollment: {
    /**
     * A​p​p​l​y​ ​n​o​w
     */
    applyNow: string;
    /**
     * C​u​r​r​i​c​u​l​u​m
     */
    curriculum: string;
    /**
     * W​h​a​t​ ​y​o​u​'​l​l​ ​l​e​a​r​n
     */
    whatYoullLearn: string;
    /**
     * S​t​a​r​t​i​n​g​ ​d​a​t​e​s
     */
    cohorts: string;
    /**
     * E​n​d​s​ ​o​n
     */
    endsOn: string;
    /**
     * E​n​t​r​y​ ​r​e​q​u​i​r​e​m​e​n​t​s
     */
    requirements: string;
    /**
     * A​t​ ​a​ ​g​l​a​n​c​e
     */
    atAGlance: string;
    /**
     * D​u​r​a​t​i​o​n
     */
    duration: string;
    /**
     * {​w​e​e​k​s​}​ ​w​e​e​k​s
     * @param {number} weeks
     */
    weeks: RequiredParams<"weeks">;
    /**
     * (​~​{​h​o​u​r​s​P​e​r​W​e​e​k​}​ ​h​o​u​r​s​ ​p​e​r​ ​w​e​e​k​)
     * @param {number} hoursPerWeek
     */
    hoursPerWeek: RequiredParams<"hoursPerWeek">;
    /**
     * M​a​x​.​ ​p​a​r​t​i​c​i​p​a​n​t​s
     */
    maxParticipants: string;
    /**
     * C​o​s​t
     */
    cost: string;
    /**
     * 1​0​0​%​ ​f​u​n​d​e​d​ ​b​y​ ​t​h​e​ ​B​u​n​d​e​s​a​g​e​n​t​u​r​ ​f​ü​r​ ​A​r​b​e​i​t
     */
    funded: string;
    status: {
      /**
       * Y​o​u​r​ ​e​n​r​o​l​l​m​e​n​t​ ​i​s​ ​p​e​n​d​i​n​g​.​ ​W​e​ ​w​i​l​l​ ​b​e​ ​i​n​ ​t​o​u​c​h​ ​s​h​o​r​t​l​y​.
       */
      pending: string;
    };
  };
  /**
   * T​h​e​m​e
   */
  theme: string;
  /**
   * s​y​s​t​e​m
   */
  systemTheme: string;
  /**
   * L​a​n​g​u​a​g​e
   */
  language: string;
  /**
   * C​h​a​n​g​i​n​g​ ​l​a​n​g​u​a​g​e​.​.​.
   */
  changingLanguage: string;
  /**
   * S​e​l​e​c​t​ ​a​n​ ​i​t​e​m​.​.​.
   */
  select: string;
  /**
   * S​u​b​m​i​t
   */
  submit: string;
  /**
   * C​o​n​f​i​r​m
   */
  confirm: string;
  /**
   * B​a​c​k
   */
  back: string;
  /**
   * C​a​n​c​e​l
   */
  cancel: string;
  meetings: {
    type: {
      /**
       * c​o​n​s​u​l​t​a​t​i​o​n
       */
      consultation: string;
      /**
       * c​o​a​c​h​i​n​g
       */
      coaching: string;
    };
    /**
     * S​c​h​e​d​u​l​e​ ​a​ ​m​e​e​t​i​n​g​ ​w​i​t​h
     */
    newMeeting: string;
    /**
     * Y​o​u​r​ ​m​e​e​t​i​n​g​ ​w​i​t​h​ ​{​n​a​m​e​}​ ​i​s​ ​s​c​h​e​d​u​l​e​d​ ​f​o​r​:
     * @param {string} name
     */
    booked: RequiredParams<"name">;
    /**
     * J​o​i​n
     */
    join: string;
    /**
     * Y​o​u​ ​w​i​l​l​ ​b​e​ ​a​b​l​e​ ​t​o​ ​j​o​i​n​ ​i​n​ ​{​t​i​m​e​}
     * @param {string} time
     */
    joinIn: RequiredParams<"time">;
    /**
     * L​e​a​v​e​ ​c​a​l​l
     */
    leave: string;
    /**
     * T​u​r​n​ ​o​n​ ​c​a​m​e​r​a
     */
    cameraOn: string;
    /**
     * T​u​r​n​ ​o​f​f​ ​c​a​m​e​r​a
     */
    cameraOff: string;
    /**
     * T​u​r​n​ ​o​n​ ​m​i​c​r​o​p​h​o​n​e
     */
    microphoneOn: string;
    /**
     * T​u​r​n​ ​o​f​f​ ​m​i​c​r​o​p​h​o​n​e
     */
    microphoneOff: string;
    /**
     * P​r​e​s​e​n​t​ ​n​o​w
     */
    presentNow: string;
    /**
     * S​t​o​p​ ​p​r​e​s​e​n​t​i​n​g
     */
    stopPresenting: string;
    /**
     * U​p​c​o​m​i​n​g​ ​m​e​e​t​i​n​g​s
     */
    upcomingMeetings: string;
  };
  measure: {
    /**
     * 1​0​0​%​ ​f​u​n​d​e​d​ ​b​y​ ​t​h​e
     */
    fundedBy: string;
  };
  address: {
    /**
     * A​d​d​r​e​s​s​ ​l​i​n​e​ ​1
     */
    line1: string;
    /**
     * A​d​d​r​e​s​s​ ​l​i​n​e​ ​2
     */
    line2: string;
    /**
     * P​o​s​t​c​o​d​e
     */
    postcode: string;
    /**
     * C​i​t​y
     */
    city: string;
    /**
     * S​t​a​t​e
     */
    state: string;
  };
  /**
   * P​r​i​v​a​c​y​ ​P​o​l​i​c​y
   */
  privacyPolicy: string;
  /**
   * T​e​r​m​s​ ​o​f​ ​U​s​e
   */
  termsOfUse: string;
  /**
   * M​i​s​s​i​o​n
   */
  mission: string;
  /**
   * I​m​p​r​i​n​t
   */
  imprint: string;
  /**
   * W​e​ ​o​n​l​y​ ​u​s​e​ ​e​s​s​e​n​t​i​a​l​ ​c​o​o​k​i​e​s​ ​t​h​a​t​ ​a​r​e​ ​n​e​c​e​s​s​a​r​y​ ​f​o​r​ ​t​h​e​ ​w​e​b​s​i​t​e​ ​t​o​ ​f​u​n​c​t​i​o​n​ ​�​�​.
   */
  cookieMessage: string;
};

export type NamespaceApplyTranslation = {
  /**
   * Y​o​u​'​r​e​ ​a​l​m​o​s​t​ ​t​h​e​r​e
   */
  almostThere: string;
  /**
   * A​p​p​l​i​c​a​t​i​o​n​ ​f​o​r
   */
  applicationFor: string;
  /**
   * �​�​ ​F​a​n​t​a​s​t​i​c​ ​n​e​w​s​!
   */
  fantasticNews: string;
  /**
   * L​e​t​'​s​ ​d​i​s​c​u​s​s​ ​t​h​e​ ​e​x​c​i​t​i​n​g​ ​j​o​u​r​n​e​y​ ​a​h​e​a​d​.​ ​P​i​c​k​ ​a​ ​t​i​m​e​ ​t​h​a​t​ ​w​o​r​k​s​ ​f​o​r​ ​y​o​u​,​ ​a​n​d​ ​I​'​l​l​ ​s​e​e​ ​y​o​u​ ​o​n​ ​t​h​e​ ​o​t​h​e​r​ ​s​i​d​e​ ​o​f​ ​t​h​e​ ​s​c​r​e​e​n​!
   */
  letsDiscuss: string;
  /**
   * L​o​o​k​i​n​g​ ​f​o​r​w​a​r​d​ ​t​o​ ​o​u​r​ ​m​e​e​t​i​n​g​!
   */
  lookingForward: string;
  /**
   * D​o​n​'​t​ ​s​e​e​ ​a​ ​t​i​m​e​ ​t​h​a​t​ ​f​i​t​s​?​ ​N​o​ ​w​o​r​r​i​e​s​,​ ​w​e​'​l​l​ ​f​i​n​d​ ​a​ ​s​l​o​t​ ​t​h​a​t​ ​w​o​r​k​s​.​ ​R​e​a​c​h​ ​o​u​t​ ​a​n​d​ ​w​e​'​l​l​ ​m​a​k​e​ ​i​t​ ​h​a​p​p​e​n​.
   */
  noTime: string;
  /**
   * Y​o​u​r​ ​a​p​p​l​i​c​a​t​i​o​n​ ​f​o​r​ ​{​m​e​a​s​u​r​e​T​i​t​l​e​}​ ​h​a​s​ ​b​e​e​n​ ​p​r​o​v​i​s​i​o​n​a​l​l​y​ ​a​p​p​r​o​v​e​d​,​ ​a​n​d​ ​n​o​w​ ​i​t​'​s​ ​t​i​m​e​ ​t​o​ ​c​a​r​v​e​ ​o​u​t​ ​y​o​u​r​ ​c​o​a​c​h​i​n​g​ ​p​a​t​h​.
   * @param {string} measureTitle
   */
  provisionallyApproved: RequiredParams<"measureTitle">;
  /**
   * P​l​e​a​s​e​ ​a​n​s​w​e​r​ ​a​ ​f​e​w​ ​q​u​e​s​t​i​o​n​s​ ​t​o​ ​h​e​l​p​ ​u​s​ ​a​s​s​e​s​s​ ​y​o​u​r​ ​e​l​i​g​i​b​i​l​i​t​y​ ​f​o​r​ ​t​h​i​s​ ​p​r​o​g​r​a​m​.​.​.
   */
  screeningQuestions: string;
  /**
   * �​�​ ​T​h​a​n​k​ ​y​o​u​ ​f​o​r​ ​a​p​p​l​y​i​n​g​!​ ​�​�
   */
  thankYou: string;
  /**
   * Y​o​u​r​ ​a​p​p​l​i​c​a​t​i​o​n​ ​i​s​ ​i​n​,​ ​a​n​d​ ​w​e​'​l​l​ ​b​e​ ​r​e​a​c​h​i​n​g​ ​o​u​t​ ​v​i​a​ ​{​e​m​a​i​l​}​ ​w​i​t​h​ ​t​h​e​ ​n​e​x​t​ ​s​t​e​p​s​.
   * @param {string} email
   */
  weWillBeInTouch: RequiredParams<"email">;
  /**
   * W​h​i​l​e​ ​y​o​u​'​r​e​ ​w​a​i​t​i​n​g​,​ ​w​h​y​ ​n​o​t​ ​d​i​v​e​ ​i​n​t​o​ ​s​o​m​e​ ​e​x​p​l​o​r​a​t​i​o​n​?
   */
  whileWaiting: string;
};

export type NamespaceSignupTranslation = {
  /**
   * W​e​l​c​o​m​e​ ​t​o​ ​{​n​a​m​e​}
   * @param {string} name
   */
  title: RequiredParams<"name">;
  /**
   * G​l​a​d​ ​y​o​u​ ​a​r​e​ ​h​e​r​e​!
   */
  subTitle: string;
  profile: {
    /**
     * W​e​ ​n​e​e​d​ ​s​o​m​e​ ​i​n​f​o​r​m​a​t​i​o​n​ ​t​o​ ​g​e​t​ ​y​o​u​r​ ​a​c​c​o​u​n​t​ ​s​e​t​ ​u​p​.​.​.
     */
    subTitle: string;
    /**
     * F​i​r​s​t​ ​n​a​m​e
     */
    firstName: string;
    /**
     * L​a​s​t​ ​n​a​m​e
     */
    lastName: string;
    /**
     * Y​o​u​r​ ​n​e​a​r​e​s​t​ ​c​i​t​y
     */
    city: string;
    /**
     * I​ ​a​c​c​e​p​t​ ​t​h​e​ ​p​r​i​v​a​c​y​ ​p​o​l​i​c​y​ ​a​n​d​ ​t​e​r​m​s​ ​o​f​ ​u​s​e
     */
    termsAccepted: string;
    /**
     * Y​o​u​ ​m​a​y​ ​s​e​n​d​ ​m​e​ ​m​a​r​k​e​t​i​n​g​ ​r​e​l​a​t​e​d​ ​e​m​a​i​l​s
     */
    emailCommunicationAccepted: string;
    /**
     * S​i​g​n​ ​U​p
     */
    signUp: string;
    /**
     * S​t​a​r​t​ ​t​y​p​i​n​g​.​.​.
     */
    emptySuggestionsText: string;
  };
};

export type Namespaces = "apply" | "signup";

type DisallowNamespaces = {
  /**
   * reserved for 'apply'-namespace\
   * you need to use the `./apply/index.ts` file instead
   */
  apply?: "[typesafe-i18n] reserved for 'apply'-namespace. You need to use the `./apply/index.ts` file instead.";

  /**
   * reserved for 'signup'-namespace\
   * you need to use the `./signup/index.ts` file instead
   */
  signup?: "[typesafe-i18n] reserved for 'signup'-namespace. You need to use the `./signup/index.ts` file instead.";
};

export type TranslationFunctions = {
  /**
   * Account
   */
  ACCOUNT: () => LocalizedString;
  /**
   * Accreditation
   */
  ACCREDITATION: () => LocalizedString;
  /**
   * Admin
   */
  ADMIN: () => LocalizedString;
  /**
   * Jobs
   */
  JOBS: () => LocalizedString;
  /**
   * Tasks
   */
  TASKS: () => LocalizedString;
  /**
   * Employers
   */
  EMPLOYERS: () => LocalizedString;
  /**
   * Skills
   */
  SKILLS: () => LocalizedString;
  skillLevels: {
    novice: {
      /**
       * Novice
       */
      title: () => LocalizedString;
      /**
       * You're new to this skill and rely on step-by-step instructions or rules to perform tasks. You may not fully understand the broader context.
       */
      description: () => LocalizedString;
    };
    advanced_beginner: {
      /**
       * Advanced Beginner
       */
      title: () => LocalizedString;
      /**
       * You have some experience and can perform tasks beyond strict rule-following. You recognize patterns but may not fully grasp their significance.
       */
      description: () => LocalizedString;
    };
    competent: {
      /**
       * Competent
       */
      title: () => LocalizedString;
      /**
       * You've developed a decent understanding of the skill and can manage complex situations. You can plan and make decisions based on your experience.
       */
      description: () => LocalizedString;
    };
    proficient: {
      /**
       * Proficient
       */
      title: () => LocalizedString;
      /**
       * You can handle most situations in this skill area confidently. You have a deeper understanding, can reflect on your actions, and adapt to new situations.
       */
      description: () => LocalizedString;
    };
    expert: {
      /**
       * Expert
       */
      title: () => LocalizedString;
      /**
       * You have a deep, intuitive understanding of the skill. You can diagnose problems and innovate solutions effortlessly. You don't rely on rules but rather your vast experience.
       */
      description: () => LocalizedString;
    };
  };
  languages: {
    /**
     * English
     */
    en: () => LocalizedString;
    /**
     * Deutsch
     */
    de: () => LocalizedString;
  };
  measures: {
    /**
     * Our courses
     */
    heading: () => LocalizedString;
    /**
     * Learn more
     */
    readMore: () => LocalizedString;
    /**
     * As an AZAV certified educational institution, we offer fully accredited courses designed to meet the highest standards of quality and effectiveness.
     */
    intro: () => LocalizedString;
  };
  enrollment: {
    /**
     * Apply now
     */
    applyNow: () => LocalizedString;
    /**
     * Curriculum
     */
    curriculum: () => LocalizedString;
    /**
     * What you'll learn
     */
    whatYoullLearn: () => LocalizedString;
    /**
     * Starting dates
     */
    cohorts: () => LocalizedString;
    /**
     * Ends on
     */
    endsOn: () => LocalizedString;
    /**
     * Entry requirements
     */
    requirements: () => LocalizedString;
    /**
     * At a glance
     */
    atAGlance: () => LocalizedString;
    /**
     * Duration
     */
    duration: () => LocalizedString;
    /**
     * {weeks} weeks
     */
    weeks: (arg: { weeks: number }) => LocalizedString;
    /**
     * (~{hoursPerWeek} hours per week)
     */
    hoursPerWeek: (arg: { hoursPerWeek: number }) => LocalizedString;
    /**
     * Max. participants
     */
    maxParticipants: () => LocalizedString;
    /**
     * Cost
     */
    cost: () => LocalizedString;
    /**
     * 100% funded by the Bundesagentur für Arbeit
     */
    funded: () => LocalizedString;
    status: {
      /**
       * Your enrollment is pending. We will be in touch shortly.
       */
      pending: () => LocalizedString;
    };
  };
  /**
   * Theme
   */
  theme: () => LocalizedString;
  /**
   * system
   */
  systemTheme: () => LocalizedString;
  /**
   * Language
   */
  language: () => LocalizedString;
  /**
   * Changing language...
   */
  changingLanguage: () => LocalizedString;
  /**
   * Select an item...
   */
  select: () => LocalizedString;
  /**
   * Submit
   */
  submit: () => LocalizedString;
  /**
   * Confirm
   */
  confirm: () => LocalizedString;
  /**
   * Back
   */
  back: () => LocalizedString;
  /**
   * Cancel
   */
  cancel: () => LocalizedString;
  meetings: {
    type: {
      /**
       * consultation
       */
      consultation: () => LocalizedString;
      /**
       * coaching
       */
      coaching: () => LocalizedString;
    };
    /**
     * Schedule a meeting with
     */
    newMeeting: () => LocalizedString;
    /**
     * Your meeting with {name} is scheduled for:
     */
    booked: (arg: { name: string }) => LocalizedString;
    /**
     * Join
     */
    join: () => LocalizedString;
    /**
     * You will be able to join in {time}
     */
    joinIn: (arg: { time: string }) => LocalizedString;
    /**
     * Leave call
     */
    leave: () => LocalizedString;
    /**
     * Turn on camera
     */
    cameraOn: () => LocalizedString;
    /**
     * Turn off camera
     */
    cameraOff: () => LocalizedString;
    /**
     * Turn on microphone
     */
    microphoneOn: () => LocalizedString;
    /**
     * Turn off microphone
     */
    microphoneOff: () => LocalizedString;
    /**
     * Present now
     */
    presentNow: () => LocalizedString;
    /**
     * Stop presenting
     */
    stopPresenting: () => LocalizedString;
    /**
     * Upcoming meetings
     */
    upcomingMeetings: () => LocalizedString;
  };
  measure: {
    /**
     * 100% funded by the
     */
    fundedBy: () => LocalizedString;
  };
  address: {
    /**
     * Address line 1
     */
    line1: () => LocalizedString;
    /**
     * Address line 2
     */
    line2: () => LocalizedString;
    /**
     * Postcode
     */
    postcode: () => LocalizedString;
    /**
     * City
     */
    city: () => LocalizedString;
    /**
     * State
     */
    state: () => LocalizedString;
  };
  /**
   * Privacy Policy
   */
  privacyPolicy: () => LocalizedString;
  /**
   * Terms of Use
   */
  termsOfUse: () => LocalizedString;
  /**
   * Mission
   */
  mission: () => LocalizedString;
  /**
   * Imprint
   */
  imprint: () => LocalizedString;
  /**
   * We only use essential cookies that are necessary for the website to function 😇.
   */
  cookieMessage: () => LocalizedString;
  apply: {
    /**
     * You're almost there
     */
    almostThere: () => LocalizedString;
    /**
     * Application for
     */
    applicationFor: () => LocalizedString;
    /**
     * 🌟 Fantastic news!
     */
    fantasticNews: () => LocalizedString;
    /**
     * Let's discuss the exciting journey ahead. Pick a time that works for you, and I'll see you on the other side of the screen!
     */
    letsDiscuss: () => LocalizedString;
    /**
     * Looking forward to our meeting!
     */
    lookingForward: () => LocalizedString;
    /**
     * Don't see a time that fits? No worries, we'll find a slot that works. Reach out and we'll make it happen.
     */
    noTime: () => LocalizedString;
    /**
     * Your application for {measureTitle} has been provisionally approved, and now it's time to carve out your coaching path.
     */
    provisionallyApproved: (arg: { measureTitle: string }) => LocalizedString;
    /**
     * Please answer a few questions to help us assess your eligibility for this program...
     */
    screeningQuestions: () => LocalizedString;
    /**
     * 🌟 Thank you for applying! 🌟
     */
    thankYou: () => LocalizedString;
    /**
     * Your application is in, and we'll be reaching out via {email} with the next steps.
     */
    weWillBeInTouch: (arg: { email: string }) => LocalizedString;
    /**
     * While you're waiting, why not dive into some exploration?
     */
    whileWaiting: () => LocalizedString;
  };
  signup: {
    /**
     * Welcome to {name}
     */
    title: (arg: { name: string }) => LocalizedString;
    /**
     * Glad you are here!
     */
    subTitle: () => LocalizedString;
    profile: {
      /**
       * We need some information to get your account set up...
       */
      subTitle: () => LocalizedString;
      /**
       * First name
       */
      firstName: () => LocalizedString;
      /**
       * Last name
       */
      lastName: () => LocalizedString;
      /**
       * Your nearest city
       */
      city: () => LocalizedString;
      /**
       * I accept the privacy policy and terms of use
       */
      termsAccepted: () => LocalizedString;
      /**
       * You may send me marketing related emails
       */
      emailCommunicationAccepted: () => LocalizedString;
      /**
       * Sign Up
       */
      signUp: () => LocalizedString;
      /**
       * Start typing...
       */
      emptySuggestionsText: () => LocalizedString;
    };
  };
};

export type Formatters = {};
